name: MyGov PDF Downloader

on:
  schedule:
    # Runs every Monday at 9 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * 2'  # Tuesday at 6 AM UTC (9 AM Kenyan time)
  workflow_dispatch:  # Allows manual trigger

jobs:
  download-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Create credentials file
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json
        
    - name: Run downloader
      env:
        GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      run: python main.py
